name: Atualizar Idade no Aniversário
on:
  schedule:
  - cron: '12 22 8 3 *' # Roda às 19:12 em GMT-3 do dia 08/03.

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer check out
        uses: actions/checkout@v2

      - name: Atualizar idade
        run: |
          # Calcular idade
          birthday_year=2002 # Ano em que nasci
          birthday_month=3  # Mês em que nasci
          birthday_day=8 # Dia em que nasci
          birthday_hour=19 # Hora em que nasci
          birthday_minute=20 # Minuto em que nasci
  
          current_year=$(date + '%Y')
          current_month=$(date + '%m')
          current_day=$(date + '%d')
          current_hour=$(date +'%H')
          current_minute=$(date +'%M')
  
          age=$((current_year - birthday_year))
          if ((current_month < birthday_month || (current_month == birthday_month && current_day < birthday_day))); then
            age=$((age - 1))
          fi
  
          # Update README with new age
          sed -i "s/I'm Nathan, a [0-9]* years old/I'm Nathan, a $age years old/" README.md
  
          # Commit and push changes
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add README.md
          git commit -m "Atualização automática de idade"
          git push
